Fix SQLite variable limit crash using json_each
SQLite has a limit on the number of bind variables allowed in a single statement (32,766). The previous implementation created a placeholder for every selected data ID, causing a crash when selecting a large number of contacts.

This CL fixes the issue by passing the ID list as a single JSON array string and using the json_each() function.

In previous implementation, the following 2 commands will throw SQLiteException,
1. adb shell "ids=$(yes 1 | head -n 33000 | tr '\n' ','); content insert --uri content://com.android.contacts.picker.sessions/sessions --bind data_ids:s:$ids --bind requester_uid:i:0"

2. adb shell content query --uri content://com.android.contacts.picker.sessions/sessions/<use_uri_from_step_1_here>

Crash log:
android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR)

Additional info:
Since SQLite 3.32.2 variable limit is increased from 999 to 32,766

From Android 12 (API 31), SQLite 3.32.2+ is in use, so the previous implementation can work with up to 32,766 contact entries.

Bug: 460461737
Flag: android.content.flags.enable_system_contacts_picker
Test: Tested the crash and fix manually, as ContactsPickerSessionProviderTest is using a Fake ContactsProvider without a real SQLite DB

Change-Id: I76abd1539e5df65790a3ede7316207eb87faacdd